# TCL File Generated by Component Editor 18.1
# Wed Dec 25 23:40:42 CET 2024
# DO NOT MODIFY


# 
# UART_Tx_Rx "UART_Tx_Rx" v3.0
#  2024.12.25.23:40:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module UART_Tx_Rx
# 
set_module_property DESCRIPTION ""
set_module_property NAME UART_Tx_Rx
set_module_property VERSION 3.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME UART_Tx_Rx
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL DE10_Lite_UART
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file DE10_Lite_UART.vhd VHDL PATH ../../../src/DE10_Lite_UART.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock Clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset Reset_n reset_n Input 1


# 
# connection point UART_conduit
# 
add_interface UART_conduit conduit end
set_interface_property UART_conduit associatedClock clock
set_interface_property UART_conduit associatedReset reset
set_interface_property UART_conduit ENABLED true
set_interface_property UART_conduit EXPORT_OF ""
set_interface_property UART_conduit PORT_NAME_MAP ""
set_interface_property UART_conduit CMSIS_SVD_VARIABLES ""
set_interface_property UART_conduit SVD_ADDRESS_GROUP ""

add_interface_port UART_conduit WR_1_Ascii wr_1_ascii Input 32
add_interface_port UART_conduit WR_0_Load wr_0_load Input 32
add_interface_port UART_conduit RD_Rx_Data rd_rx_data Output 32
add_interface_port UART_conduit Uart_Rx uart_rx Input 1
add_interface_port UART_conduit Uart_Tx uart_tx Output 1

